//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipList.Formlar
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFirmList
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string sector { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string address { get; set; }
    }
}
