//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipList.Formlar
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTask()
        {
            this.TblDetailTask = new HashSet<TblDetailTask>();
        }
    
        public int ID { get; set; }
        public Nullable<int> commissioner { get; set; }
        public Nullable<int> employee { get; set; }
        public string statement { get; set; }
        public string statu { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> passive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDetailTask> TblDetailTask { get; set; }
        public virtual TblEmployee TblEmployee { get; set; }
        public virtual TblEmployee TblEmployee1 { get; set; }
    }
}
